name: MoodlePlus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List project files
        run: ls -la

      - name: Simulate build step
        run: echo "Project build successful"

      - name: Simulate test step
        run: echo "No automated tests yet"
